# Generated by Django 6.0.4 on 2026-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_goal_start_date_cardiosession_strava'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiosession',
            name='map_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
