# Generated by Django 6.0.2 on 2026-05-08 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_workouttemplate_templateexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2026, 5, 8, 9, 4, 59, 339556, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
